"""empty message

Revision ID: 0e27a5b4a8e2
Revises: be6d85181d87
Create Date: 2021-06-23 17:45:05.401274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e27a5b4a8e2'
down_revision = 'be6d85181d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'exam', 'clazz', ['clazz_id'], ['id'])
    op.create_foreign_key(None, 'exam', 'course', ['course_id'], ['id'])
    op.create_foreign_key(None, 'exam', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'result', 'exam', ['exam_id'], ['id'])
    op.create_foreign_key(None, 'student_score', 'exam', ['exam_id'], ['id'])
    op.add_column('user', sa.Column('isdelete', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('isforbid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isforbid')
    op.drop_column('user', 'isdelete')
    op.drop_constraint(None, 'student_score', type_='foreignkey')
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_constraint(None, 'exam', type_='foreignkey')
    # ### end Alembic commands ###
