"""empty message

Revision ID: 2bcd77b47b17
Revises: 612b9b54421d
Create Date: 2021-06-20 17:28:53.137306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bcd77b47b17'
down_revision = '612b9b54421d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'exam', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'result', 'exam', ['exam_id'], ['id'])
    op.create_foreign_key(None, 'student_score', 'exam', ['exam_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_score', type_='foreignkey')
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.drop_constraint(None, 'exam', type_='foreignkey')
    # ### end Alembic commands ###
