"""empty message

Revision ID: 612b9b54421d
Revises: b5b5a9dbb73f
Create Date: 2021-06-20 16:13:40.750472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612b9b54421d'
down_revision = 'b5b5a9dbb73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('udatetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.add_column('exam', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exam', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'result', 'exam', ['exam_id'], ['id'])
    op.create_foreign_key(None, 'student_score', 'exam', ['exam_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_score', type_='foreignkey')
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_column('exam', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
