"""empty message

Revision ID: b5b5a9dbb73f
Revises: 
Create Date: 2021-06-13 10:59:30.835800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b5a9dbb73f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_name', sa.String(length=150), nullable=False),
    sa.Column('course', sa.String(length=50), nullable=False),
    sa.Column('clazz', sa.String(length=50), nullable=False),
    sa.Column('teacher', sa.String(length=50), nullable=False),
    sa.Column('exam_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_num', sa.Integer(), nullable=False),
    sa.Column('s_total', sa.Float(), nullable=False),
    sa.Column('s_everage', sa.Float(), nullable=False),
    sa.Column('s_max', sa.Float(), nullable=False),
    sa.Column('s_min', sa.Float(), nullable=False),
    sa.Column('s_youxiu', sa.Float(), nullable=False),
    sa.Column('s_hege', sa.Float(), nullable=False),
    sa.Column('down_60', sa.Integer(), nullable=False),
    sa.Column('s60_70', sa.Integer(), nullable=False),
    sa.Column('s70_80', sa.Integer(), nullable=False),
    sa.Column('s80_90', sa.Integer(), nullable=False),
    sa.Column('s90_100', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_score')
    op.drop_table('result')
    op.drop_table('exam')
    # ### end Alembic commands ###
