"""empty message

Revision ID: be6d85181d87
Revises: 2bcd77b47b17
Create Date: 2021-06-20 21:44:20.531183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be6d85181d87'
down_revision = '2bcd77b47b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clazz',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('c_name')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cou_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cou_name')
    )
    op.add_column('exam', sa.Column('clazz_id', sa.Integer(), nullable=True))
    op.add_column('exam', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exam', 'course', ['course_id'], ['id'])
    op.create_foreign_key(None, 'exam', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'exam', 'clazz', ['clazz_id'], ['id'])
    op.drop_column('exam', 'teacher')
    op.drop_column('exam', 'course')
    op.drop_column('exam', 'clazz')
    op.create_foreign_key(None, 'result', 'exam', ['exam_id'], ['id'])
    op.create_foreign_key(None, 'student_score', 'exam', ['exam_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_score', type_='foreignkey')
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.add_column('exam', sa.Column('clazz', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('exam', sa.Column('course', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('exam', sa.Column('teacher', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_column('exam', 'course_id')
    op.drop_column('exam', 'clazz_id')
    op.drop_table('course')
    op.drop_table('clazz')
    # ### end Alembic commands ###
